import { test, expect } from "@playwright/test";

import { ensureSiteSettingsAddress, getSeededProductPath } from "./helpers.js";

const getJsonLdBlocks = async (page) => {
  const scripts = await page
    .locator('script[type="application/ld+json"]')
    .allTextContents();
  return scripts.map((s) => JSON.parse(s));
};

// Product/Category/etc. only render <Seo> once their async data has
// loaded, so checking meta tags immediately after goto() races the
// fetch — wait for the page's own h1 first, same as a real user would
// need to before seeing the content at all.
const gotoAndWaitForContent = async (page, path) => {
  await page.goto(path);
  await expect(page.getByRole("heading", { level: 1 }).first()).toBeVisible({
    timeout: 10000,
  });
};

test.describe("Unique titles and meta descriptions", () => {
  // Product path is resolved per-test below (async, so it can't be a
  // plain string in this array — see getSeededProductPath's comment on
  // why it can't be hardcoded either).
  const pages = [
    { path: "/", label: "Home" },
    { path: "/category/bedsheets", label: "Category" },
    { path: null, label: "Product" },
    { path: "/articles", label: "Articles" },
  ];

  for (const { path, label } of pages) {
    test(`${label} page has a title and exactly one meta description`, async ({
      page,
    }) => {
      const resolvedPath =
        path ?? (await getSeededProductPath()).path;
      await gotoAndWaitForContent(page, resolvedPath);

      const title = await page.title();
      expect(title.length).toBeGreaterThan(0);

      // Regression guard: index.html previously had a static meta
      // description that Helmet never removed, so every page carried
      // two duplicate <meta name="description"> tags.
      const descriptionTags = page.locator('meta[name="description"]');
      await expect(descriptionTags).toHaveCount(1);
      const description = await descriptionTags.getAttribute("content");
      expect(description).toBeTruthy();
    });
  }

  test("Home and Product page titles and descriptions are different from each other", async ({
    page,
  }) => {
    await gotoAndWaitForContent(page, "/");
    const homeTitle = await page.title();
    const homeDescription = await page
      .locator('meta[name="description"]')
      .getAttribute("content");

    const { path: productPath } = await getSeededProductPath();
    await gotoAndWaitForContent(page, productPath);
    const productTitle = await page.title();
    const productDescription = await page
      .locator('meta[name="description"]')
      .getAttribute("content");

    expect(productTitle).not.toBe(homeTitle);
    expect(productTitle).toContain("Luxury Cotton Bedsheet");
    expect(productDescription).not.toBe(homeDescription);
  });
});

test.describe("Structured data", () => {
  test("product page includes Product and BreadcrumbList JSON-LD", async ({
    page,
  }) => {
    const { path: productPath } = await getSeededProductPath();
    await gotoAndWaitForContent(page, productPath);

    const blocks = await getJsonLdBlocks(page);
    const types = blocks.map((b) => b["@type"]);

    expect(types).toContain("Product");
    expect(types).toContain("BreadcrumbList");

    const product = blocks.find((b) => b["@type"] === "Product");
    expect(product.name).toContain("Luxury Cotton Bedsheet");
  });

  test("visible breadcrumb trail matches the BreadcrumbList JSON-LD exactly", async ({
    page,
  }) => {
    const { path: productPath } = await getSeededProductPath();
    await gotoAndWaitForContent(page, productPath);

    const visibleCrumbs = await page
      .getByLabel("Breadcrumb")
      .locator("li")
      .allTextContents();

    const blocks = await getJsonLdBlocks(page);
    const breadcrumbList = blocks.find((b) => b["@type"] === "BreadcrumbList");
    const jsonLdNames = breadcrumbList.itemListElement
      .sort((a, b) => a.position - b.position)
      .map((item) => item.name);

    expect(visibleCrumbs).toEqual(jsonLdNames);
  });

  test("homepage includes LocalBusiness/HomeGoodsStore structured data", async ({
    page,
  }) => {
    // Home.jsx only emits this JSON-LD once SiteSettings.address is
    // set — nothing seeds it, so ensure it here rather than assume a
    // freshly seeded site already has one configured.
    await ensureSiteSettingsAddress();
    await gotoAndWaitForContent(page, "/");
    const blocks = await getJsonLdBlocks(page);
    const types = blocks.map((b) => b["@type"]);
    expect(
      types.some((t) => t === "HomeGoodsStore" || t === "LocalBusiness"),
    ).toBe(true);
  });
});

test.describe("Crawling infrastructure", () => {
  // /sitemap.xml is generated by client/api/sitemap.js, a Vercel
  // serverless function — it only runs under Vercel (production, or
  // `vercel dev`), not under the plain `vite dev` this suite (and CI)
  // runs against, where the request just falls through to the SPA's
  // index.html. Verify manually against a real deployment instead.
  test.skip(
    "sitemap.xml exists and lists at least one product URL",
    async ({ request }) => {
      const res = await request.get("http://localhost:5173/sitemap.xml");
      expect(res.status()).toBe(200);
      const body = await res.text();
      expect(body).toContain("<urlset");
      expect(body).toContain("/product/");
    },
  );

  // robots.txt Disallow-ing a URL blocks Googlebot from ever crawling it,
  // which means it can never see that page's own <Seo noindex/> tag in
  // the first place — combining the two is contradictory (Google's own
  // guidance) and can leave the URL showing up in results anyway, as a
  // bare link with no snippet, if discovered externally. Only /admin
  // (which carries no noindex tag of its own, and isn't meant to be
  // crawled at all) should still be hard-Disallow'd; everything else
  // relies on noindex alone, verified per-page below.
  test("robots.txt disallows only /admin, not pages that already carry noindex", async ({
    request,
  }) => {
    const res = await request.get("http://localhost:5173/robots.txt");
    expect(res.status()).toBe(200);
    const body = await res.text();

    expect(body).toContain("Disallow: /admin");

    for (const path of [
      "/account",
      "/cart",
      "/checkout",
      "/search",
      "/compare",
    ]) {
      expect(body).not.toContain(`Disallow: ${path}`);
    }
  });

  test("account/cart/compare/wishlist/login pages carry a noindex meta tag", async ({
    page,
  }) => {
    for (const path of ["/cart", "/compare", "/wishlist", "/login"]) {
      await page.goto(path);
      await expect(page.locator('meta[name="robots"]')).toHaveAttribute(
        "content",
        /noindex/,
      );
    }
  });
});
